export default [
    {
        id: '1',
        title: 'arroyo',
        description: 'foto de un arroyo de la patagonia',
        image: require('../assets/landscapes/arroyo.jpg'),
        // image: '../assets/landscapes/arroyo.jpg',
    },
    {
        id: '2',
        title: 'arroyo2',
        description: 'foto de un arroyo de la patagonia',
        image: require('../assets/landscapes/arroyo2.jpg'),
        // image: '../assets/landscapes/arroyo2.jpg',
    },
    // {
    //     id: '3',
    //     title: 'Canchita de Futbol, el filo del cerro catedral, cerca dele refugio Frey',
    //     description: 'foto del filo del cerro catedral, en la patagonia',
    // //     image: require('../assets/landscapes/canchita-de-futbol.jpg'),
//     image: require('../assets/landscapes/canchita-de-futbol.jpg'),
    // },
    {
        id: '4',
        title: 'jakob',
        description:'foto del refugio jabok en bariloche',
        image: require('../assets/landscapes/jakob.jpg'),
        // image: '../assets/landscapes/jakob.jpg',
    },
    {
        id: '5',
        title: 'jakob2',
        description:'foto del refugio jabok en bariloche',
        image: require('../assets/landscapes/jakob1.jpg'),
        // image: '../assets/landscapes/jakob1.jpg',
    },
    {
        id: '6',
        title: 'lago frey',
        description:'foto del lago frey' ,
        image: require('../assets/landscapes/lago-frey.jpg'),
        // image: '../assets/landscapes/lago-frey.jpg' ,
    },
    // {
    //     id: '7',
    //     title: 'mirada del doctor',
    //     description: 'foto de la mirada del doctor, cerca de la laguna ilon en el parqwue nacional nahuel huapi',
    // //     image: require('../../assets/landscapes/mirada-del-doctor.jpg'),
//     image: require('../../assets/landscapes/mirada-del-doctor.jpg'),
    // },
    // {
    //     id: '8',
    //     title: 'paso de las nubes',
    //     description: 'foto del paso de las nubes en el cerro tronador, parque nacional nahuel huapi, argentina',
    // //     image: require('../../assets/landscapes/paso-de-las-nubes.jpg'),
//     image: require('../../assets/landscapes/paso-de-las-nubes.jpg'),
    // },
];
